name: Pull Request Gate

on: pull_request

env:
  JDA_REGISTRY: 'https://jdasoftware.jfrog.io/jdasoftware/api/npm/npm/'
  AZURE_APP_NAME: "my-app-mfe"
jobs:
  test:
    name: Run PR formatting, linting, and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MY_CREDENTIALS }} # Replace with your credentials
      - uses: Azure/get-keyvault-secrets@v1.1
        with:
          keyvault: "my-azure-vault" # Replace with your azure vault 
          secrets: '*'
      - name: checkout dependant DS actions
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PLAT_LUI_GH_ACTIONS_CHECKOUT_PAT }}
          repository: JDA-Product-Development/ds-github-actions
          path: ds-actions
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: ./ds-actions/copyright-applier
      - name: Set npm config
        run: |
          npm config set _auth="${{env.artifactoryAuth}}"
          npm config set always-auth
          npm config set registry "${{env.artifactoryNpmUrl}}"
          npm config set @jda:registry "${{env.artifactoryNpmUrl}}"
          npm config set email no-reply@jda.com
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --prefer-offline --no-audit
      - name: Check linting
        run: npm run lint
      - name: Execute Test Coverage
        run: npm test
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
  scan-dependencies:
    name: Dependencies Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MY_CREDENTIALS }} # Replace with your credentials
      - uses: Azure/get-keyvault-secrets@v1.1
        with:
          keyvault: "my-azure-vault" # Replace with your azure vault 
          secrets: '*'
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set npm config
        run: |
          npm config set _auth="${{env.artifactoryAuth}}"
          npm config set always-auth
          npm config set registry "${{env.artifactoryNpmUrl}}"
          npm config set @jda:registry "${{env.artifactoryNpmUrl}}"
          npm config set email no-reply@jda.com
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --prefer-offline --no-audit
      - name: Perform Blackduck scan
        uses: blackducksoftware/github-action@2.0.1
        with:
          args: '--blackduck.url="${{env.blackduckUrl}}"
          --blackduck.api.token="${{env.blackduckAuth}}"
          --detect.project.name=plat-lui-${{env.AZURE_APP_NAME}}
          --detect.project.version.name=master
          --detect.blackduck.signature.scanner.upload.source.mode=false
          --detect.blackduck.signature.scanner.exclusion.pattern.search.depth=0
          --detect.tools.excluded=SIGNATURE_SCAN
          --detect.project.tags=TAG1,TAG2
          --detect.wait.for.results=false
          --detect.risk.report.pdf=false
          --detect.npm.include.dev.dependencies=false
          --detect.report.timeout=3600
          --detect.project.user.groups=admins,users
          --detect.project.codelocation.unmap=true'
  finalize:
    name: Finalize run
    runs-on: ubuntu-latest
    needs: [test, scan-dependencies]
    steps:
      - run: echo Done running workflow